# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    my_user_provider:
          class: "%my_user_provider.class%"
          arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id}]
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.registration:
          class: AppBundle\Form\RegistrationType
          tags:
                - { name: form.type, alias: app_user_registration }

    app.registration_listener:
            class: AppBundle\EventListener\RegistrationListener
            arguments: []
            tags:
                - { name: kernel.event_subscriber }

    get_set_method_normalizer:
            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
            public: false
            tags:
                - { name: serializer.normalizer }
    #registering my twig extensions
    #app.twig.extension.vars_extension:
    #       class: AppBundle\Twig\Extension\VarsExtension
    #       arguments: ["@service_container"]
    #       tags:
    #            - { name: 'twig.extension' }

    #app.twig_extension.array_extension:
    #     class: AppBundle\Twig\Extension\ArrayExtension
    #     public: false
    #     tags:
    #        - { name: 'twig.extension' }

    app.new_saludo:
        autowire: true
        class: AppBundle\Service\MessageGenerator
        #resource: '../../src/AppBundle/Service/MessageGenerator'
        public: false
        tags:
            - { name: 'saludos' }

    AppBundle\Service\MessageGenerator: '@app.new_saludo'

    app.favorites:
        autowire: true
        class: AppBundle\Service\MyFavoritesService
        public: false
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: 'my_favorites' }

    AppBundle\Service\MyFavoritesService: '@app.favorites'

    app.friends:
        autowire: true
        class: AppBundle\Service\MyFriendsService
        public: false
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: 'my_friends' }

    AppBundle\Service\MyFriendsService: '@app.friends'

    app.registry:
        autowire: true
        class: AppBundle\Service\MyRegistyService
        public: false
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: 'my_registry' }

    AppBundle\Service\MyRegistyService: '@app.registry'

    app.profile:
        autowire: true
        class: AppBundle\Service\ProfileService
        public: false
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: 'profile' }

    AppBundle\Service\ProfileService: '@app.profile'