<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BussinessRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BussinessRepository extends EntityRepository
{

  /**
   * @param $id_distro
   *
   * @return array
   */
  public function getBizByDistroId($id_distro) {
    return $this->getEntityManager()
                ->createQuery("SELECT b FROM AppBundle:Bussiness WHERE id_distro = :distro")
                ->setParameter("distro", $id_distro)->getResult();

  }

  /**
   * @param $id_registar
   *
   * @return array
   */
  public function getBizByRegistarId($id_registar){
    return $this->getEntityManager()
                ->createQuery("SELECT b FROM AppBundle:Bussiness WHERE id_registar = :distro")
                ->setParameter("distro", $id_registar)->getResult();
  }

}
