<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

  /**
   * @param \AppBundle\Entity\User $user
   * @return array
   */
  public function getMyFriends(User $user){
    return $this->getFriendsById($user->getId());
  }

  /**
   * @param integer $user_id
   * @return array
   */
  public function getFriendsById($user_id){

    $collection1 = $this->getEntityManager()
         ->createQuery("SELECT u FROM AppBundle:Friends f
                            JOIN AppBundle:User u
                            WITH u.id = f.user_id
                            WHERE f.user_id = :user_id")
         ->setParameters(array(
           'user_id' => $user_id,

         ))
         ->getResult();

    $collection2 = $this->getEntityManager()
         ->createQuery("SELECT u FROM AppBundle:Friends f
                            JOIN AppBundle:User u
                            WITH u.id = f.user_id
                            WHERE f.friend_user_id = :user_id")
         ->setParameters(array(
           'user_id' => $user_id,

         ))
         ->getResult();

    $collection3 = new ArrayCollection(
      array_merge($collection1, $collection2)
    );

    return $collection3;


  }
}
